onlyBuiltDependencies:
  - esbuild
  - maplibre-gl
  - vue-demi

catalog:
  pinia: ^3.0.1
  vue: ^3.5.13
  vue-i18n: ^11.1.2
  vue-router: ^4.5.0

catalogs:
  ui:
    "@netpro/ui": ^0.0.0
  shadcn-vue:
    "@unovis/ts": 1.5.1
    "@unovis/vue": 1.5.1
    "@vee-validate/zod": ^4.15.0
    "@vueuse/core": ^11.3.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    embla-carousel-vue: ^8.5.2
    reka-ui: ^2.1.1
    tailwind-merge: ^2.5.5
    tailwindcss-animate: ^1.0.7
    vaul-vue: ^0.4.1
    vee-validate: ^4.15.0
    vue-sonner: ^1.3.0
    zod: ^3.24.2
  shadcn-vue-dev:
    lucide-vue-next: ^0.484.0
  shadcn-vue-peer:
    "@formkit/auto-animate": ^0.8.2
    "@internationalized/date": ^3.7.0
    "@tanstack/vue-table": ^8.20.5
  ui-tree:
    "@atlaskit/pragmatic-drag-and-drop": ^1.4.0
    "@atlaskit/pragmatic-drag-and-drop-hitbox": ^1.0.3
  icons:
    "@iconify-prerendered/vue-lucide": ^0.28.1732777651
    "@iconify-prerendered/vue-svg-spinners": ^0.28.1673787445
    "@iconify-prerendered/vue-vscode-icons": ^0.28.1732777911
    "@netpro/icons-trinity": ^0.0.0
    "@radix-icons/vue": ^1.0.0
  fonts:
    "@fontsource-variable/inter": ^5.1.0
    "@fontsource-variable/noto-sans-sc": ^5.1.0
    "@fontsource-variable/noto-sans-tc": ^5.1.0
    "@netpro/jf-openhuninn": ^2.1.0
  vite6:
    "@tsconfig/node22": ^22.0.1
    "@types/node": ^22.13.14
    "@vitejs/plugin-vue": ^5.2.1
    "@vitest/eslint-plugin": 1.1.37
    "@vue/eslint-config-prettier": ^10.2.0
    "@vue/eslint-config-typescript": ^14.5.0
    "@vue/shared": ^3.5.13
    "@vue/test-utils": ^2.4.6
    "@vue/tsconfig": ^0.7.0
    autoprefixer: ^10.4.21
    eslint: ^9.21.0
    eslint-plugin-vue: ^10.0.0
    npm-run-all2: ^7.0.2
    postcss: ^8.5.3
    prettier: ^3.5.3
    tailwindcss: ^3.4.17
    typescript: ~5.8.2
    unplugin-vue-components: ^28.4.1
    vite: ^6.2.3
    vite-plugin-vue-devtools: ^7.7.2
    vitest: ^3.0.8
    vue-tsc: ^2.2.8