catalogs:
  css:
    '@tailwindcss/postcss': ^4.1.18
    '@tailwindcss/vite': ^4.1.18
    autoprefixer: ^10.4.23
    postcss: ^8.5.6
    tailwind-merge: ^3.4.0
    tailwindcss: ^4.1.18
    tw-animate-css: ^1.4.0
  fonts:
    '@fontsource-variable/inter': ^5.2.5
    '@fontsource-variable/noto-sans-sc': ^5.2.5
    '@fontsource-variable/noto-sans-tc': ^5.2.5
  icons:
    lucide-vue-next: ^0.562.0
  shadcn-vue:
    '@unovis/ts': ^1.6.2
    '@unovis/vue': ^1.6.2
    '@vee-validate/zod': ^4.15.1
    '@vueuse/core': ^13.9.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    embla-carousel-vue: ^8.6.0
    reka-ui: ^2.7.0
    vaul-vue: ^0.4.1
    vee-validate: ^4.15.1
    vue-sonner: ^2.0.9
    zod: ^4.2.1
  shadcn-vue-peer:
    '@formkit/auto-animate': ^0.9.0
    '@internationalized/date': ^3.10.1
    '@tanstack/vue-table': ^8.21.3
  ui-tree:
    '@atlaskit/pragmatic-drag-and-drop': ^1.6.1
    '@atlaskit/pragmatic-drag-and-drop-hitbox': ^1.0.3
  vite:
    '@tsconfig/node22': ^22.0.5
    '@types/node': ^22.19.3
    '@vitejs/plugin-vue': ^6.0.3
    '@vue/tsconfig': ^0.8.1
    npm-run-all2: ^8.0.4
    prettier: ^3.7.4
    typescript: ~5.9.3
    unplugin-vue-components: ^28.8.0
    vite: ^7.3.1
    vite-plugin-vue-devtools: ^8.0.5
    vue-tsc: ^3.2.2
  vue:
    pinia: ^3.0.3
    vue: ^3.5.26
    vue-i18n: ^11.1.12
    vue-router: ^4.6.4
  vue-eslint:
    '@vue/eslint-config-prettier': ^10.2.0
    '@vue/eslint-config-typescript': ^14.6.0
    eslint: ^9.33.0
    eslint-plugin-vue: ~10.4.0
    jiti: ^2.5.1
  vue-test:
    '@types/jsdom': ^21.1.7
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/eslint-plugin': ^1.3.4
    '@vitest/ui': ^3.2.4
    '@vue/test-utils': ^2.4.6
    jsdom: ^27.4.0
    vitest: ^4.0.17

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - vue-sonner
  - reka-ui
  - tailwindcss
  - '@tailwindcss/vite'
  - vite

onlyBuiltDependencies:
  - esbuild
  - '@tailwindcss/oxide'
