minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - vue-sonner

onlyBuiltDependencies:
  - esbuild
  - "@tailwindcss/oxide"

catalogs:
  vue:
    pinia: ^3.0.3
    vue: ^3.5.22
    vue-i18n: ^11.1.12
    vue-router: ^4.5.1
  shadcn-vue:
    "@unovis/ts": ^1.6.1
    "@unovis/vue": ^1.6.1
    "@vee-validate/zod": ^4.15.1
    "@vueuse/core": ^13.9.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    embla-carousel-vue: ^8.6.0
    reka-ui: ^2.5.1
    vaul-vue: ^0.4.1
    vee-validate: ^4.15.1
    vue-sonner: ^2.0.9
    zod: ^4.1.11
  shadcn-vue-peer:
    "@formkit/auto-animate": ^0.9.0
    "@internationalized/date": ^3.10.0
    "@tanstack/vue-table": ^8.21.3
  css:
    "@tailwindcss/postcss": ^4.1.6
    "@tailwindcss/vite": ^4.1.13
    autoprefixer: ^10.4.21
    postcss: ^8.5.6
    tailwindcss: ^4.1.13
    tailwind-merge: ^3.3.0
    tw-animate-css: ^1.4.0
  ui-tree:
    "@atlaskit/pragmatic-drag-and-drop": ^1.6.1
    "@atlaskit/pragmatic-drag-and-drop-hitbox": ^1.0.3
  icons:
    lucide-vue-next: ^0.544.0
  fonts:
    "@fontsource-variable/inter": ^5.2.5
    "@fontsource-variable/noto-sans-sc": ^5.2.5
    "@fontsource-variable/noto-sans-tc": ^5.2.5
  vite:
    "@tsconfig/node22": ^22.0.2
    "@types/node": ^22.15.18
    "@vitejs/plugin-vue": ^6.0.1
    "@vue/tsconfig": ^0.8.1
    npm-run-all2: ^8.0.4
    prettier: ^3.5.3
    typescript: ~5.8.3
    unplugin-vue-components: ^28.5.0
    vite: ^7.1.7
    vite-plugin-vue-devtools: ^8.0.2
    vue-tsc: ^3.1.0
  vue-eslint:
    '@vue/eslint-config-prettier': ^10.2.0
    '@vue/eslint-config-typescript': ^14.6.0
    eslint: ^9.33.0
    eslint-plugin-vue: ~10.4.0
    jiti: ^2.5.1
  vue-test:
    '@types/jsdom': ^21.1.7
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/eslint-plugin': ^1.3.4
    '@vitest/ui': ^3.2.4
    '@vue/test-utils': ^2.4.6
    jsdom: ^26.1.0
    vitest: ^3.2.4