onlyBuiltDependencies:
  - esbuild
  - maplibre-gl
  - vue-demi
  - "@tailwindcss/oxide"

catalog:
  pinia: ^3.0.1
  vue: ^3.5.13
  vue-i18n: ^11.1.2
  vue-router: ^4.5.0

catalogs:
  ui:
    "@netpro/ui": ^0.0.0
  shadcn-vue:
    "@unovis/ts": 1.5.1
    "@unovis/vue": 1.5.1
    "@vee-validate/zod": ^4.15.0
    "@vueuse/core": ^13.7.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    embla-carousel-vue: ^8.5.2
    reka-ui: ^2.2.1
    tailwind-merge: ^3.3.0
    vaul-vue: ^0.4.1
    vee-validate: ^4.15.0
    vue-sonner: ^1.3.2
    zod: ^3.24.4
  shadcn-vue-dev:
    lucide-vue-next: ^0.510.0
  shadcn-vue-peer:
    "@formkit/auto-animate": ^0.8.2
    "@internationalized/date": ^3.8.0
    "@tanstack/vue-table": ^8.21.3
    # for tailwindcss 3
    "tailwindcss-animate": ^1.0.7
    # for tailwindcss 4
    tw-animate-css: ^1.2.9
  ui-tree:
    "@atlaskit/pragmatic-drag-and-drop": ^1.6.1
    "@atlaskit/pragmatic-drag-and-drop-hitbox": ^1.0.3
  icons:
    "@iconify-prerendered/vue-lucide": ^0.28.1747201005
    "@iconify-prerendered/vue-svg-spinners": ^0.28.1673787445
    "@iconify-prerendered/vue-vscode-icons": ^0.28.1747201363
    "@netpro/icons-trinity": ^0.0.0
    "@radix-icons/vue": ^1.0.0
  fonts:
    "@fontsource-variable/inter": ^5.2.5
    "@fontsource-variable/noto-sans-sc": ^5.2.5
    "@fontsource-variable/noto-sans-tc": ^5.2.5
    "@netpro/jf-openhuninn": ^2.1.0
  vite6:
    "@tailwindcss/postcss": ^4.1.6
    "@tailwindcss/vite": ^4.1.8
    "@tsconfig/node22": ^22.0.1
    "@types/jsdom": ^21.1.7
    "@types/node": ^22.15.18
    "@vitejs/plugin-vue": ^5.2.4
    "@vitest/eslint-plugin": 1.1.44
    "@vue/eslint-config-prettier": ^10.2.0
    "@vue/eslint-config-typescript": ^14.5.0
    "@vue/shared": ^3.5.13
    "@vue/test-utils": ^2.4.6
    "@vue/tsconfig": ^0.7.0
    autoprefixer: ^10.4.21
    eslint: ^9.22.0
    eslint-plugin-vue: ^10.0.0
    jiti: ^2.4.2
    jsdom": ^26.1.0
    npm-run-all2: ^8.0.4
    postcss: ^8.5.3
    prettier: ^3.5.3
    tailwindcss: ^4.1.8
    typescript: ~5.8.3
    unplugin-vue-components: ^28.5.0
    vite: ^6.3.5
    vite-plugin-vue-devtools: ^7.7.6
    vitest: ^3.1.3
    vue-tsc: ^2.2.10